[platformio]
default_envs = matrixportal_s3_custom

[env:matrixportal_s3_custom]
extends = env:adafruit_matrixportal_esp32s3
build_flags = ${env:adafruit_matrixportal_esp32s3.build_flags}
  ;; Front buttons: Up = GPIO6, Down = GPIO7 (active low, type 2 = push w/ pullup)
  -D BTNPIN=6,7
  -D BTNTYPE=2,2
  ;; STEMMA QT / Qwiic I2C connector
  -D I2CSDAPIN=16
  -D I2CSCLPIN=17
